rdkcentral/firebolt-certification-app

- src/App.js
[FIRECERT-1576](https://ccp.sys.comcast.net/browse/FIRECERT-1576)
> FIRECERT-1576 SpeechSynthesisErrorEvent in mfos

- src/utils/Utils.js
> Fix erroneous error messages in Utils.js

- src/MenuBuilder.js
Fix for Launch MoneyBadger App button not displayed in UI
[FIRECERT-1549](https://ccp.sys.comcast.net/browse/FIRECERT-1549)
> FIRECERT-1549: Fix Launch MoneyBadger button

- .github/workflows/build-and-unit-test.yml
- src/App.js
- src/IntentReader.js
- src/MenuBuilder.js
- src/Test_Runner.js
- src/utils/Utils.js
- test/unit/IntentReader.test.js
> Merge Dev to Master 2nd Nov 2023

- src/IntentReader.js
- src/utils/Utils.js
* Adds the ability to pass standalone mode in from intent
* Also reportingId will override the mac address for the standalone report name by default
> Feature - ability to set standalone mode through intent

- package-lock.json
- package.json
> SDK 1.0.0-next.2

- src/utils/Utils.js
> add reportingid to catch block

- package-lock.json
- package.json
- test/jest.config.js
> update security vulnerability and jtest

- package-lock.json
- package.json
- src/utils/Utils.js
- test/jest.config.js
> Merge Dev to Master 16th Nov 2023

- src/LifeCycleHistory.js
- src/utils/Utils.js
Removed console log and pass query.params.task instead of query.task in discovery.onNavigate intent logic
[SYSTEST-9628](https://your-jira-domain.com/browse/SYSTEST-9628)
> Clean up Standalone mode

- src/LifeCycleHistory.js
- src/utils/Utils.js
Update discovery.onNavigateTo intent to send query.params if query.params.task exists and remove console log
> Hotfix/standalone discovery.onNavigateTo

- package-lock.json
- package.json
- src/App.js
- src/EventInvocation.js
- src/IntentReader.js
- src/MethodInvoker.js
- src/pubsub/handlers/HealthCheckHandler.js
- src/utils/Utils.js
- test/jest.config.js
- test/unit/EventInvocation.test.js
Reverts rdkcentral/firebolt-certification-app#38
> Revert "merge dev in"

- docs/Documentation.md
- docs/Reporting.md
Adds reporting documentation to FCA.
[SYSTEST-9549](https://ccp.sys.comcast.net/browse/SYSTEST-9549)
> SYSTEST-9549 - Reporting Documentation

- src/App.js
- src/LifeCycleHistory.js
- src/PubSubCommunication.js
- test/jest.config.js
- webpack.dev.js
- webpack.prod.js
Reverts rdkcentral/firebolt-certification-app#50
> Revert "FIRECERT-1744-New Support Cold launch for different SDK versions via …"

- src/App.js
- src/LifeCycleHistory.js
- src/PubSubCommunication.js
- test/jest.config.js
- webpack.dev.js
- webpack.prod.js
Reverts rdkcentral/firebolt-certification-app#55
> Revert "Revert "FIRECERT-1744-New Support Cold launch for different SDK versions via …""

- src/utils/Utils.js
> FIRECERT-1823 Handle undefined MAC for S3 report upload in FCA

- src/IntentReader.js
- src/pubsub/handlers/VisibilityStateHandler.js
Ticket - https://ccp.sys.comcast.net/browse/FIRECERT-1773
> FIRECERT-1773 Fetch window values for app transitions

- package.json
- plugins/pubsub.md
- src/EventInvocation.js
- src/LifeCycleHistory.js
- src/MethodFilters.js
- src/MethodInvoker.js
- src/PubSubCommunication.js
- src/Test_Runner.js
- src/constant.js
- src/pubSubClient.js
- src/source/errorSchema.json
- src/utils/Utils.js
- test/unit/MethodInvoker.test.js
> FIRECERT-1861-Task3: FCA Changes in sanity report for sky device

- package.json
> FIRECERT-1820 updated sdk version to 1.1.0

- src/App.js
- src/IntentReader.js
- src/utils/Utils.js
> Added for standalonePrefix

- plugins/config.js
- plugins/startupScripts/activateMockFirebolt.js
- src/IntentReader.js
> FIRECERT-1722 CoreSDK suite on MFOS - FCA standalone actions

- plugins/pubsub.md
- src/pubSubClient.js
This PR aims to add a default pubSubClient as a template into FCA to work with a simple pub sub server.
> Add pubSubClient and update docs

- src/Test_Runner.js
- test/unit/test_runner.test.js
[Issue-2001](https://your-jira-domain.com/browse/Issue-2001)
> FIRECERT-2001: Point 3 - [FCS] Method filter lists not honored for executions

- src/Test_Runner.js
- src/constant.js
[FIRECERT-1993](https://ccp.sys.comcast.net/browse/FIRECERT-1993)
> FIRECERT-1993: [FCA] Improve logging in mochawesome reports

- src/App.js
- src/FireboltTransportInvoker.js
- src/MenuBuilder.js
[FIRECERT-2014](Firecert 2014: Tag 0.8.1 bug fixes)
> Firecert 2014: Tag 0.8.1 bug fixes

- test/unit/IntentReader.test.js
> Intent reader fix 0.8.1

- .github/workflows/build-and-deploy.yml
- .github/workflows/clean-up-closed-pr-deployments.yml
- .github/workflows/lint-and-unit-tests.yml
This PR aims to accomplish the task of building FCA when commits are pushed to dev and prod along with when PRs are opened against dev. Here is an overview of how it works:
1. A PR is created against the dev branch of FCA. Or a commit is made to `dev` or `main`.
2. GitHub Actions runs the `Build and Deploy FCA` workflow.
3. The workflow installs dependencies and creates a build of the app in the dist/web directory. This build directory is then committed and pushed to the branch `github-io-deployment` which serves as the deployment branch.
4. When a PR is closed, we remove that directory from the deployment branch.
> Deploy Build with GitHub Action

- src/IntentReader.js
- src/pubsub/handlers/LifecycleMethodHandler.js
- test/unit/IntentReader.test.js
> FIRECERT:2103-Tag 0.17.1

- src/pubsub/handlers/LifecycleMethodHandler.js
> FIRECERT-2103-0.17.1: Import fix

- src/IntentReader.js
- src/pubsub/handlers/LifecycleMethodHandler.js
- test/unit/IntentReader.test.js
> FIRECERT:2103-Tag-012.0

- src/IntentReader.js
- src/pubsub/handlers/LifecycleMethodHandler.js
- test/unit/IntentReader.test.js
> FIRECERT:2103-Tag 0.11.0

- src/IntentReader.js
- src/pubsub/handlers/LifecycleMethodHandler.js
- test/unit/IntentReader.test.js
> FIRECERT:2103-Tag 0.13.0

- src/IntentReader.js
- src/pubsub/handlers/LifecycleMethodHandler.js
- test/unit/IntentReader.test.js
> FIRECERT:2103-Tag 0.14.0 

- src/IntentReader.js
- src/pubsub/handlers/LifecycleMethodHandler.js
- test/unit/IntentReader.test.js
> FIRECERT:2103-Tag 0.15.0 

- src/IntentReader.js
- src/pubsub/handlers/LifecycleMethodHandler.js
- test/unit/IntentReader.test.js
> FIRECERT:2103-Tag 0.16.0

- src/IntentReader.js
- src/pubsub/handlers/LifecycleMethodHandler.js
- test/unit/IntentReader.test.js
> FIRECERT:2103-Tag 0.17.0

- src/IntentReader.js
- src/pubsub/handlers/LifecycleMethodHandler.js
- test/unit/IntentReader.test.js
> FIRECERT:2103-Tag 1.0.0

- test/unit/IntentReader.test.js
> FIRECERT-2103: Unit test failure fix

- src/pubsub/handlers/LifecycleMethodHandler.js
> FIRECERT-2103: Fix

- src/pubsub/handlers/LifecycleMethodHandler.js
> FIRECERT:2103 - Fix

- src/pubsub/handlers/VisibilityStateHandler.js
> FIRECERT-1789: [FCS] - Use window values for language

- src/pubsub/handlers/LifecycleMethodHandler.js
> Constants Import fix

- src/App.js
- src/IntentReader.js
- src/utils/Utils.js
> FIRECERT-2152 - [FCA] Authentication.token to authentication.root for standalone Tag- 0.11.0

- src/App.js
- src/IntentReader.js
- src/utils/Utils.js
> FIRECERT-2152 - [FCA] Authentication.token to authentication.root for standalone Tag-0.12.0

- src/App.js
- src/IntentReader.js
- src/utils/Utils.js
> FIRECERT-2152 - [FCA] Authentication.token to authentication.root for standalone Tag-0.13.0

- src/App.js
- src/IntentReader.js
- src/utils/Utils.js
> FIRECERT-2152 - [FCA] Authentication.token to authentication.root for standalone Tag -0.14.0

- src/App.js
- src/IntentReader.js
- src/utils/Utils.js
> FIRECERT-2152 - [FCA] Authentication.token to authentication.root for standalone Tag-0.15.0

- src/App.js
- src/IntentReader.js
- src/utils/Utils.js
> FIRECERT-2152 - [FCA] Authentication.token to authentication.root for standalone Tag-0.16.0

- src/App.js
- src/IntentReader.js
- src/utils/Utils.js
> FIRECERT-2152 - [FCA] Authentication.token to authentication.root for standalone Tag-0.17.0

- src/App.js
- src/IntentReader.js
- src/utils/Utils.js
> FIRECERT-2152 - [FCA] Authentication.token to authentication.root for standalone Tag-0.17.1

- src/App.js
- src/IntentReader.js
- src/utils/Utils.js
https://ccp.sys.comcast.net/browse/FIRECERT-2152
> FIRECERT-2152 - [FCA] Authentication.token to authentication.root for standalone Tag-1.0.0

- src/App.js
- src/IntentReader.js
- src/utils/Utils.js
> FIRECERT-2152 - [FCA] Authentication.token to authentication.root for standalone Tag-0.9.0

- src/App.js
- src/IntentReader.js
- src/utils/Utils.js
> FIRECERT-2152 - [FCA] Authentication.token to authentication.root for standalone Tag - 0.10.0

- src/App.js
- src/IntentReader.js
- src/utils/Utils.js
> FIRECERT-2152 - [FCA] Authentication.token to authentication.root for standalone Tag - 0.8.1

- plugins/pubsub.md
- src/App.js
- src/pubSubClient.js
> copying changes from 9779 branch

- src/App.js
- src/MenuBuilder.js
> FIRECERT-2152: Changes to test lifecycle.read

- src/App.js
- src/EventInvocation.js
- src/MethodInvoker.js
- src/Test_Runner.js
- src/pubsub/handlers/CallMethodHandler.js
- src/pubsub/handlers/GetEventResponse.js
- src/pubsub/handlers/LifecycleMethodHandler.js
- src/pubsub/handlers/RegisterEventHandler.js
- test/unit/CallMethodHandler.test.js
- test/unit/EventInvocation.test.js
- test/unit/GetEventResponse.test.js
- test/unit/MethodInvoker.test.js
- test/unit/RegisterEventHandler.test.js
- test/unit/test_runner.test.js
[FIRECERT-2027](https://ccp.sys.comcast.net/browse/FIRECERT-2027)
> FIRECERT-2027: Porting schema validation migration changes to 0.11.0 tag

- src/App.js
- src/EventInvocation.js
- src/MethodInvoker.js
- src/Test_Runner.js
- src/pubsub/handlers/CallMethodHandler.js
- src/pubsub/handlers/GetEventResponse.js
- src/pubsub/handlers/LifecycleMethodHandler.js
- src/pubsub/handlers/RegisterEventHandler.js
- test/unit/CallMethodHandler.test.js
- test/unit/EventInvocation.test.js
- test/unit/GetEventResponse.test.js
- test/unit/MethodInvoker.test.js
- test/unit/RegisterEventHandler.test.js
- test/unit/test_runner.test.js
https://ccp.sys.comcast.net/browse/FIRECERT-2027
> FIRECERT-2027: Porting schema validation migration changes

- src/App.js
- src/EventInvocation.js
- src/MethodInvoker.js
- src/Test_Runner.js
- src/pubsub/handlers/CallMethodHandler.js
- src/pubsub/handlers/GetEventResponse.js
- src/pubsub/handlers/LifecycleMethodHandler.js
- src/pubsub/handlers/RegisterEventHandler.js
- test/unit/CallMethodHandler.test.js
- test/unit/EventInvocation.test.js
- test/unit/GetEventResponse.test.js
- test/unit/MethodInvoker.test.js
- test/unit/RegisterEventHandler.test.js
- test/unit/test_runner.test.js
https://ccp.sys.comcast.net/browse/FIRECERT-2027
> FIRECERT-2027: Porting schema validation migration changes to 0.13.0

- src/App.js
- src/EventInvocation.js
- src/MethodInvoker.js
- src/Test_Runner.js
- src/pubsub/handlers/CallMethodHandler.js
- src/pubsub/handlers/GetEventResponse.js
- src/pubsub/handlers/LifecycleMethodHandler.js
- src/pubsub/handlers/RegisterEventHandler.js
- test/unit/CallMethodHandler.test.js
- test/unit/EventInvocation.test.js
- test/unit/GetEventResponse.test.js
- test/unit/MethodInvoker.test.js
- test/unit/RegisterEventHandler.test.js
- test/unit/test_runner.test.js
> FIRECERT-2027: Port schema validation migration changes to tags

- src/App.js
- src/EventInvocation.js
- src/MethodInvoker.js
- src/Test_Runner.js
- src/pubsub/handlers/CallMethodHandler.js
- src/pubsub/handlers/GetEventResponse.js
- src/pubsub/handlers/LifecycleMethodHandler.js
- src/pubsub/handlers/RegisterEventHandler.js
- test/unit/CallMethodHandler.test.js
- test/unit/EventInvocation.test.js
- test/unit/GetEventResponse.test.js
- test/unit/MethodInvoker.test.js
- test/unit/RegisterEventHandler.test.js
- test/unit/test_runner.test.js
https://ccp.sys.comcast.net/browse/FIRECERT-2027
> FIRECERT-2027: Porting schema validation migration changes to 0.8.1

- src/App.js
- src/EventInvocation.js
- src/MethodInvoker.js
- src/Test_Runner.js
- src/pubsub/handlers/CallMethodHandler.js
- src/pubsub/handlers/GetEventResponse.js
- src/pubsub/handlers/LifecycleMethodHandler.js
- src/pubsub/handlers/RegisterEventHandler.js
- test/unit/CallMethodHandler.test.js
- test/unit/EventInvocation.test.js
- test/unit/GetEventResponse.test.js
- test/unit/MethodInvoker.test.js
- test/unit/RegisterEventHandler.test.js
- test/unit/test_runner.test.js
https://ccp.sys.comcast.net/browse/FIRECERT-2027
> FIRECERT-2027: Porting schema validation migration changes to 0.10.0

- README.md
- src/App.js
- src/EventInvocation.js
- src/MethodInvoker.js
- src/Test_Runner.js
- src/pubsub/handlers/CallMethodHandler.js
- src/pubsub/handlers/GetEventResponse.js
- src/pubsub/handlers/LifecycleMethodHandler.js
- src/pubsub/handlers/RegisterEventHandler.js
- test/unit/CallMethodHandler.test.js
- test/unit/EventInvocation.test.js
- test/unit/GetEventResponse.test.js
- test/unit/MethodInvoker.test.js
- test/unit/RegisterEventHandler.test.js
- test/unit/test_runner.test.js
Migrate schema validation to FCS and
[FIRECERT-2025](https://ccp.sys.comcast.net/browse/FIRECERT-2025)
> FIRECERT-2025: Migrate schema validation to FCS

- test/unit/GetEventResponse.test.js
- test/unit/RegisterEventHandler.test.js
> FIRECERT-2027: Port schema validation migration changes to tags 

- src/Test_Runner.js
- src/constant.js
> Mocha-report logs corrections

- src/source/censorData.json
- src/utils/Utils.js
- test/jest.config.js
- webpack.dev.js
- webpack.prod.js
> censorDataFix : Adding local copy of censorData

- package.json
> winstonVersion : Making winston version static

- src/Test_Runner.js
> fix: [FCA] Data is not censored in context field inside json file

- package.json
> Added lz-string library

- package.json
> Removed lzutf8 dependency

- package.json
> 1.0.0 Removed lzutf8 dependency

- package.json
> 0.11.0 Removed lzutf8 dependency 

- package.json
> 0.12.0 Removed lzutf8 dependency

- package.json
> 0.13.0 Removed lzutf8 dependency

- package.json
> 0.14.0 Removed lzutf8 dependency

- package.json
> 0.15.0 Removed lzutf8 dependency

- package.json
> 0.16.0 Removed lzutf8 dependency

- package.json
> 0.17.0 Removed lzutf8 dependency

- package.json
> 1.1.0 Removed lzutf8 dependency

- package.json
> Change FCA version to 1.3.0 SDK

- src/Test_Runner.js
> fix: Fixed Invalid duration in sanity

- src/Test_Runner.js
> fix: TAG-1.0.0 Fixed Invalid duration in sanity

- src/EventInvocation.js
- src/MethodInvoker.js
- src/Test_Runner.js
- src/source/errorSchema.json
- src/utils/Utils.js
> SDK Error schema handling in sanity and module to TAG-1.0.0

- src/EventInvocation.js
- src/MethodInvoker.js
- src/Test_Runner.js
- src/source/errorSchema.json
- src/utils/Utils.js
> SDK Error schema handling in sanity and module to TAG-0.10.0

- src/EventInvocation.js
- src/MethodInvoker.js
- src/Test_Runner.js
- src/source/errorSchema.json
- src/utils/Utils.js
> SDK Error schema handling in sanity and module to TAG-0.8.1

- src/Test_Runner.js
- src/ValidationView.js
- src/constant.js
- src/pubsub/handlers/RunTestHandler.js
- src/utils/Utils.js
- test/unit/test_runner.test.js
> feat: Sanity report logging

- src/App.js
- src/IntentReader.js
- test/jest.config.js
- webpack.dev.js
- webpack.prod.js
> added functionality to fetch openRPC download url based on extension sdk

- src/pubsub/handlers/clearEventHandler.js
> fix: Fixing clear event listener issue

- package.json
- src/App.js
- src/IntentReader.js
- src/utils/Utils.js
- test/jest.config.js
- webpack.dev.js
- webpack.prod.js
> EntOS and extension SDK service call

- package.json
> updated winston library

- package.json
- src/App.js
- src/IntentReader.js
- src/utils/Utils.js
- test/jest.config.js
- webpack.dev.js
- webpack.prod.js
> Latest dev changes

- src/App.js
- src/LifeCycleHistory.js
- src/constant.js
- src/utils/Utils.js
> Accept SAT in urlParam or Intent for FCA 0.8.1

- src/App.js
- src/LifeCycleHistory.js
- src/constant.js
- src/utils/Utils.js
> Accept SAT in urlParam or Intent for FCA 1.0.0

- src/App.js
- src/LifeCycleHistory.js
- src/constant.js
- src/utils/Utils.js
> Accept SAT in urlParam or Intent for FCA 0.10.0

- src/App.js
- src/LifeCycleHistory.js
> Accept SAT in urlParam or Intent for FCA 1.1.0

- src/MenuBuilder.js
- src/MethodFilters.js
- src/constant.js
- test/unit/MethodFilters.test.js
> Fix for the triggering badger events in the sanity

- src/constant.js
> Display enums present in extensionSDK and Firebolt execution in sanity report

- package.json
> fix: Update package.json for jsconschema version

- package.json
- src/constant.js
> Dev to Main merge 1/17

- src/Card.js
- src/utils/Utils.js
> Fix: To display invoker response in UI for Sanity

- package.json
- src/Card.js
* fix : Show response in UI for Invokers
* Update package.json for Firebolt SDK 1.5.0 (#277)
* logs for censor
* Update Utils.js
* Update Utils.js
* Revoked logs
---------
> Merge main to dev on March 18, 2025

- src/FireboltExampleInvoker.js
- src/MethodInvoker.js
- src/Test_Runner.js
> utility function to check for params and map with SDK api

- src/FireboltExampleInvoker.js
- src/Test_Runner.js
> FCA edge-entos fixes

- src/utils/Utils.js
> Streamline reporting for FCA

- src/ValidationView.js
- src/utils/Utils.js
> Merge dev to main - May 22 2025

- src/ValidationView.js
- src/utils/Utils.js
> Back merge main into dev

- src/FireboltTransportInvoker.js
- src/constant.js
transport invoker side changes for new sdk
Ticket - https://ccp.sys.comcast.net/browse/FIRECERT-3119
> new sdk transport invocation changes

- package.json
> Update sdk version

- package.json
- webpack.dev.js
- webpack.prod.js
> Dev to main on Oct 2nd
